# Generated by Django 5.2.7 on 2026-04-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Numer inwentarzowy')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Srodek trwaly',
                'verbose_name_plural': 'Srodki trwale',
                'ordering': ['-added_at'],
            },
        ),
    ]
