# Generated by Django 5.2.7 on 2026-04-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rebuild_asset_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='inventory_number',
            field=models.CharField(error_messages={'unique': 'Składnik o tym numerze inwentarzowym już istnieje.'}, max_length=100, unique=True, verbose_name='Numer inwentarzowy'),
        ),
    ]
