# Generated by Django 5.2.7 on 2026-04-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_inventory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Kategoria'),
        ),
    ]
