# Generated by Django 5.2.7 on 2026-04-25 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_asset_category'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='locations.location', verbose_name='Lokalizacja relacyjna'),
        ),
    ]
