# Generated by Django 5.2.7 on 2026-05-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Środek trwały'), ('low_value', 'Wyposażenie / niskocenne'), ('intangible', 'WNiP'), ('quantity', 'Ilościówka'), ('other', 'Inne')], db_index=True, max_length=32, verbose_name='Rodzaj'),
        ),
    ]
