# Generated by Django 5.2.7 on 2026-05-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_asset_asset_type_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='record_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Ilość ewidencyjna'),
        ),
    ]
