# Generated by Django 5.2.7 on 2026-05-08 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_asset_last_inventory_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Czas')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], max_length=50, verbose_name='Typ zdarzenia')),
                ('description', models.CharField(max_length=255, verbose_name='Opis')),
                ('old_value', models.TextField(blank=True, verbose_name='Poprzednia wartość')),
                ('new_value', models.TextField(blank=True, verbose_name='Nowa wartość')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Pole')),
                ('source_object_type', models.CharField(blank=True, max_length=100, verbose_name='Typ źródła')),
                ('source_object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID źródła')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='assets.asset', verbose_name='Środek')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Wpis historii środka',
                'verbose_name_plural': 'Wpisy historii środków',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
