# Generated by Django 5.2.7 on 2026-05-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0013_assethistoryentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assethistoryentry",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("moved", "Moved"),
                ],
                max_length=50,
                verbose_name="Typ zdarzenia",
            ),
        ),
    ]
