# Generated by Django 5.2.7 on 2026-05-10 07:02

from django.db import migrations, models
from django.db.models import Case, F, Value, When


def initialize_current_quantity(apps, schema_editor):
    Asset = apps.get_model("assets", "Asset")
    Asset.objects.update(
        current_quantity=Case(
            When(last_inventory_quantity__isnull=False, then=F("last_inventory_quantity")),
            When(record_quantity__isnull=False, then=F("record_quantity")),
            default=Value(1),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_alter_assethistoryentry_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_quantity',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Aktualna ilość'),
        ),
        migrations.RunPython(initialize_current_quantity, migrations.RunPython.noop),
    ]
