# Generated by Django 5.2.7 on 2026-05-15 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_assetattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetServiceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, verbose_name='Powód / opis')),
                ('alert_date', models.DateField(db_index=True, verbose_name='Data alertu')),
                ('status', models.CharField(choices=[('active', 'Aktywny'), ('done', 'Wykonany'), ('cancelled', 'Anulowany')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data zamknięcia')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_alerts', to='assets.asset', verbose_name='Środek')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Zamknięty przez')),
            ],
            options={
                'verbose_name': 'Alert serwisowy',
                'verbose_name_plural': 'Alerty serwisowe',
                'ordering': ['alert_date', 'created_at'],
            },
        ),
    ]
