# Generated by Django 5.2.7 on 2026-05-19 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_assetattachment_formal_document_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDepreciationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Włączono naliczanie')),
                ('method', models.CharField(blank=True, choices=[('linear', 'Liniowa'), ('one_time', 'Jednorazowa')], max_length=20, verbose_name='Metoda')),
                ('kst_category', models.CharField(blank=True, max_length=120, verbose_name='KST / kategoria')),
                ('initial_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Wartość początkowa (zł)')),
                ('residual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Wartość rezydualna (zł)')),
                ('depreciation_start_date', models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia')),
                ('annual_rate_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Stawka roczna (%)')),
                ('useful_life_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Okres (miesiące)')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_plan', to='assets.asset', verbose_name='Środek')),
            ],
            options={
                'verbose_name': 'Plan amortyzacji',
                'verbose_name_plural': 'Plany amortyzacji',
            },
        ),
    ]
