# Generated by Django 5.2.7 on 2026-05-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_assetdepreciationplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdepreciationplan',
            name='annual_depreciation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Roczny odpis amortyzacyjny (zł)'),
        ),
        migrations.AddField(
            model_name='assetdepreciationplan',
            name='monthly_depreciation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Miesięczny odpis amortyzacyjny (zł)'),
        ),
    ]
