# Generated by Django 5.2.7 on 2026-05-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_assetdepreciationplan_stored_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdepreciationplan',
            name='kst_category',
            field=models.CharField(blank=True, max_length=120, verbose_name='KŚT'),
        ),
    ]
