# Generated by Django 5.2.7 on 2026-04-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='asset_changes_require_approval',
            field=models.BooleanField(default=False, verbose_name='Zmiany srodkow wymagaja akceptacji'),
        ),
    ]
