# Generated by Django 5.2.7 on 2026-10-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_asset_changes_require_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="interface_mode",
            field=models.CharField(
                choices=[("full", "Pełna wersja"), ("lite", "Lite")],
                default="full",
                max_length=16,
                verbose_name="Tryb interfejsu",
            ),
        ),
    ]
