from django.urls import path

from .views import (
    AssetChangeRequestListView,
    AssetChangeRequestDetailView,
    AssetArchiveListView,
    AssetCreateView,
    AssetListView,
    AssetUpdateView,
    asset_attachment_delete,
    asset_attachment_download,
    asset_attachment_upload,
    asset_bulk_move_api,
    asset_bulk_withdraw_api,
    asset_change_approve,
    asset_change_bulk_approve,
    asset_change_bulk_reject,
    asset_change_reject,
    asset_depreciation_plan,
    asset_detail,
    asset_export_csv_api,
    asset_generate_lt_pdf,
    asset_import,
    asset_import_template,
    asset_labels_pdf,
    asset_list_api,
    asset_lt_document,
    asset_restore,
    asset_service_alert_create,
    asset_service_alert_resolve,
    asset_withdraw,
)


app_name = "assets"

urlpatterns = [
    path("api/assets/", asset_list_api, name="api-list"),
    path("api/assets/export/", asset_export_csv_api, name="api-export"),
    path("api/assets/bulk-move/", asset_bulk_move_api, name="api-bulk-move"),
    path("api/assets/bulk-withdraw/", asset_bulk_withdraw_api, name="api-bulk-withdraw"),
    path("", AssetListView.as_view(), name="list"),
    path("assets/archive/", AssetArchiveListView.as_view(), name="archive"),
    path("assets/changes/", AssetChangeRequestListView.as_view(), name="change-list"),
    path("assets/changes/bulk-approve/", asset_change_bulk_approve, name="bulk-approve"),
    path("assets/changes/bulk-reject/", asset_change_bulk_reject, name="bulk-reject"),
    path("assets/changes/<int:pk>/", AssetChangeRequestDetailView.as_view(), name="change-detail"),
    path("assets/changes/<int:pk>/approve/", asset_change_approve, name="change-approve"),
    path("assets/changes/<int:pk>/reject/", asset_change_reject, name="change-reject"),
    path("assets/add/", AssetCreateView.as_view(), name="create"),
    path("assets/<int:pk>/edit/", AssetUpdateView.as_view(), name="update"),
    path("assets/<int:id>/restore/", asset_restore, name="asset-restore"),
    path("assets/<int:id>/withdraw/", asset_withdraw, name="asset-withdraw"),
    path("assets/<int:id>/", asset_detail, name="detail"),
    path("assets/labels/pdf/", asset_labels_pdf, name="labels-pdf"),
    path("assets/archive/lt/", asset_lt_document, name="archive-lt"),
    path("assets/archive/lt/generate/", asset_generate_lt_pdf, name="lt-generate"),
    path("assets/import/", asset_import, name="import"),
    path("assets/import/template/", asset_import_template, name="import-template"),
    path("assets/<int:asset_id>/attachments/upload/", asset_attachment_upload, name="attachment-upload"),
    path("assets/<int:asset_id>/attachments/<int:attachment_id>/download/", asset_attachment_download, name="attachment-download"),
    path("assets/<int:asset_id>/attachments/<int:attachment_id>/delete/", asset_attachment_delete, name="attachment-delete"),
    path("assets/<int:asset_id>/service-alerts/create/", asset_service_alert_create, name="service-alert-create"),
    path("service-alerts/<int:alert_id>/resolve/", asset_service_alert_resolve, name="service-alert-resolve"),
    path("assets/<int:asset_id>/depreciation/", asset_depreciation_plan, name="depreciation-plan"),
]
