# Generated by Django 5.2.7 on 2026-04-22 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('code', models.CharField(blank=True, editable=False, max_length=32, unique=True, verbose_name='Kod')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='locations.location', verbose_name='Lokalizacja nadrzędna')),
            ],
            options={
                'verbose_name': 'Lokalizacja',
                'verbose_name_plural': 'Lokalizacje',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['parent', 'name'], name='location_parent_name_idx'), models.Index(fields=['is_active', 'name'], name='location_active_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('parent', 'name'), name='location_unique_name_per_parent')],
            },
        ),
    ]
