# Generated by Django 5.2.7 on 2026-05-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Pełna nazwa organizacji')),
                ('short_name', models.CharField(blank=True, max_length=64, verbose_name='Krótka nazwa / skrót')),
                ('report_footer', models.TextField(blank=True, verbose_name='Stopka raportów i dokumentów')),
            ],
            options={
                'verbose_name': 'Dane organizacji',
                'verbose_name_plural': 'Dane organizacji',
            },
        ),
    ]
